### PR TITLE
Add script injection option to hide cpu cores and toggle option to disable spdy support header

### LINKED ISSUE #461: Add an option to hide CPU cores number
Javascript reveals our CPU cores number (even with a CPU override option) as we can see here : 

- https://www.browserleaks.com/javascript (Hardware Concurrency)
and here
- http://webkay.robinlinus.com/ (Computer Hardware)

Then I apply for an option to hide or fake this (maybe there is already an option directly in about:config?)

### LINKED ISSUE #478: Determine if SPDY support should be disabled within Firefox?
The [SPDY](https://en.wikipedia.org/wiki/SPDY) networking protocol, which is supposed to reduce load latency on webpages is yet another way of determining your real profile regardless if the user agent is spoofed. Google developed the protocol (no surprise) which is now being deprecated and support has been removed from Chrome version 51. 

As seen below, the request header shows the user agent is set to Edge, but because `network.http.spdy.enabled` is set to `true` by default, Google knows that i'm using Firefox which is seen in the response header.

screenshot

### PR DESCRIPTION
**Pull request by DrunkenSasquatch**
Everything has been tested and works, I'm willing to change the names or locations in which the options have been set.

The CPU Cores option only hides the numbers at this point because I wasn't sure whether we want to spoof it. I can spoof the values before each page load by adding the following in intercept.js:

```java
//get even number between 2-8//
var getCore = Math.ceil(Math.random() * 4) * 2;

if(frameOptions.spoofCores && wlInjectStates.spoofCores == false) 
            utils.defineProp(window,"Navigator","hardwareConcurrency",getCore);
```
Closes #461 #478 
Link to XPI: https://github.com/DrunkenSasquatch/random-agent-spoofer/releases

### CODE REVIEW

**Comment by dillbyrne** [comment]
Hi @DrunkenSasquatch :+1: . Thanks this looks good, I'm guessing in changing the code you forgot to use the values you pass in.   

``` 
if(frameOptions.hideCores && wlInjectStates.hideCores == false)
     utils.defineProp(window,"Navigator","hardwareConcurrency","");

```


should be 

```
if(frameOptions.spoofCores && wlInjectStates.spoofCores == false)  utils.defineProp(window,"Navigator","hardwareConcurrency",frameOptions.hideCores);
```

Also I was thinking that maybe having a dropdown to specify the cores, similar to the way the spoof via header is implemented. 

The dropdown options could be 2,4 ,8 and random. It also opens up options later on to add a profile option later that would use core values defined in the profile, that would be particularly useful for mobile platforms.  

Thoughts ?

**Comment by DrunkenSasquatch** [comment]
Good Idea. Like a checkbox + dropdown like this?

```html
<p>
     <input type="checkbox" id="cores" data-invertvalue="false" data-prefname="extensions.agentSpoof.spoofCores" />
     <label for="cores">Spoof CPU Cores</label>
     <select id="coresdd" class="dd" data-prefname="extensions.agentSpoof.spoofCoresdd">
			<option value="random">Random</option>
			<option value="2">2</option>
			<option value="4">4</option>
			<option value="6">6</option>
			<option value="8">8</option>
     </select>
```
untitled

**Comment by dillbyrne** [comment]
Actually it is probably easier to simply have the dropdown on its own  without the checkbox like the screen size dropdown and add a `Default` option, which would not spoof. A `None` option could also be added to the dropdown and it would use an empty string if selected.

The pass the selected value in using params.spoofCores in Chrome.js.

The do the logic in intercept.js, something like
```
if (frameOptions.spoofCores != "default" && wlInjectStates.webSocket == false){
     
    if (frameOptions.spoofCores == "none")
         utils.defineProp(window,"Navigator","hardwareConcurrency","");
    else
        utils.defineProp(window,"Navigator","hardwareConcurrency",frameOptions.spoofCores);
} 
```

Instead of setting a checkbox in Panel.js you can use `setSelectedIndexByValue` and it will take care of ensuring there correct option is set in the GUI upon startup.

**Comment by DrunkenSasquatch** [comment]
@dillbyrne 👍 Awesome. I have it working now, although when I select a certain number from the list, the numbers are being returned in string value rather than numeric value. I'm not sure if this really matters or not.

It still works either way 😄

**Comment by DrunkenSasquatch** [comment]
I might close this PR and start a new one since this a mess and is outdated.

**Pull request closed without merging**
