### PR TITLE
Update Chrome and Firefox versions

### PR DESCRIPTION
**Pull request by dedkamaroz**
Update Chrome and Firefox versions to latest stable releases

### CODE REVIEW

**Comment by dedkamaroz** [comment]
@dillbyrne Please review and merge updated Chrome and Firefox versions in the useragents file

**Comment by RdKoyoe** [comment]
@dedkamaroz have it been merged?

**Comment by forkoz** [comment]
everything turns to firefox 53 and chrome 58, this is junk... but thanks for letting me know what file to edit.

**Review by forkoz — CHANGES_REQUESTED** [review]
you can't just find and replace ALL of the versions with the same one.

**Comment by dedkamaroz** [comment]
Obviously by now firefox is up to 55 and Chrome is up to 60 but I disagree that my update is junk.
Each entry that I tried to update consists of a different OS version, and when coupled with either the current version of Firefox or Chrome, presents a unique user agent.
Either way this update is a damn sight better than how the extension is currently - with a 2 year old browser version.

**Comment by dillbyrne** [comment]
@dedkamaroz @forkoz . I appreciate the effort with the PR and all but I am no longer maintaining RAS. There is no point in merging it now as FF 57 will be out soon enough. I have moved to the brave browser myself as most of the addons I use or developed will no longer work and many of them rely on modifying about:config entries.

If anyone wants to fork RAS and try to port it they are free to do so.

**Pull request closed without merging**
