### PR TITLE
CSS and markup cleanup (mostly)

### PR DESCRIPTION
**Pull request by alct**
### Updated/cleaned up CSS

Cleaned up the CSS to ease future updates: commented the code, regrouped rules, deleted redundant and or useless properties, alphabetically re-ordered properties when needed,...

Slightly updated some styles.

### Removed useless hr element

Self-explanatory.

### Removed useless whitespace before attribute

Self-explanatory.

### Replaced dash character by "en dash"

Replaced "-" by "–" as the "collapse" symbol. It is larger, therefore more visible.

### Fixed whitespace/tab mixing, cleaned line endings, added new line at the end of file

Self-explanatory.

### Removed useless whitespaces among attributes

Self-explanatory.

### Fixed whitespace/tab mixing, fixed markup, fixed indentation, commented the code

This file was a complete mess - to say the least. Fixed a series of problems regarding whitespace/tab mixing and homogenized the markup to ease future updates.

### CODE REVIEW

**Comment by dillbyrne** [comment]
Hey @alct thanks for your work on this :+1: . 

One or two points I have:

The `hr` element was there to distinguish certain options from others in the same group as they had an effect on the other options. 

I would prefer to leave out the `normalize.css` dependency because most of the library is for cross compatibility between different browsers. While I understand that it can help with different versions of firefox, it also makes more work if the RAS UI breaks with a future update to firefox as I have now have to check two css files to isolate the problem. I would rather manage the inconsistencies between different firefox versions myself as I have been as it is much quicker to fix issues. 

I'll manually merge this without the normalize.css when I get a chance

**Comment by dillbyrne** [comment]
@alct having looked at the changes I'll keep the normalize.css and merge when I get a chance

**Comment by alct** [comment]
I'd be happy to maintain the CSS related stuff if it is too much of a burden for you.

As I said in another thread #154 , RAS is useful to me and I recommend it extensively. I'm here to help in the long run.

The current HTML (CSS) would really, really, need a rewrite from scratch. Beyond this pull request, I've tried to patch here and there last night, it took hours (because I had to update the JS as well) and I finally given up because it was taking too much time. It's a miracle it hasn't blown up in your face yet.

If a glimpse of what needs to be fixed can convince you:

- block and inline level elements are mixed in every possible manner: the code wouldn't pass the validator and it's very likely to create inconsistencies in the styles. In other words, you shouldn't even care about using normalize or not, the current HTML/CSS is a timebomb ;
- `class` and `id`s are wrongly used: `id` should only be used when they're absolutely required for interaction (JS, label or anchors) because they override CSS `class`es. `class`es should be used everywhere else because you can have several of them on the same element, can reuse them and there are specific CSS(3) selectors to help deal with them ;
- there's a lot a useless markup, complexifying the code (not only the HTML but the JS as well) and thus, rising the barrier for potential contributors ;
- `<br>`, `<br>` everywhere: `<br>` must not be used for styling purpose ;
- missing labels for given inputs ;
- ...

I'm willing to help fix these issues but we'll have to work together.

**Comment by alct** [comment]
Regarding the `<hr>`, to quote [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr):

> The HTML `<hr>` element represents a thematic break between paragraph-level elements (for example, a change of scene in a story, or a shift of topic with a section)

In the profile tab, hidden radio boxes have the same purpose as the top radio boxes, we shouldn't make a distinction by creating a visual separation.

**Comment by dillbyrne** [comment]
@alct I see the `<hr>` in question was only on the profiles section I initially thought it was removing all of them including the one on the headers and whitelist tabs where I find they help separate the content so you can ignore my comment regarding that.

I don't mind maintaining it but your help is appreciated. I initially thought the `normalize.css` was another file needed but I see it is included above and should not be much of an issue.

I know the codebase well so I have no fear of it blowing up :smile: . Functionality was my primary concern and since it only had to work on firefox and since it was not a website I was not too concerned about ensuring if it would pass validation as long as it done the job and worked on firefox.

There are many elements I need to get and set by `id` so that is why there are many elements with the id attribute. I'm no CSS expert so I acknowledge that it may not be the best approach and appreciate the help on that front.

Sometimes the complexity is dictated by the functionality and other times is dictated by the UI. Where the HTML/CSS is concerned it is generally dictated by the UI though as I have acknowledged above my approach may not always be the best one.

As I said I'll merge the changes above when I get a chance and then take it from there.

Thanks again for the help and feedback

**Comment by alct** [comment]
Cool :) I'll wait for your merge.

**Comment by dillbyrne** [comment]
Hello @alct I have merged your changes. For some reason your commits are not showing. If you would really like them to show up I can roll back and re try it to see if that fixes it, let me know. Either way I will of course be crediting / thanking you in the next release.

**Comment by dillbyrne** [comment]
Your commits now show up. Thanks again for your work on this :+1:

**Comment by alct** [comment]
Did you increase the indentation in the HTML file on purpose or is it a side effect of the merging? (we could earn some space and improve the code readability by reducing it a bit)

Don't hesitate to let me know, I'll create a pull request tomorrow morning if needed (if we've got to do it, the sooner would be the better).

**Comment by dillbyrne** [comment]
It must have happened due to the merge. I [reduced the indentation](https://github.com/dillbyrne/random-agent-spoofer/blob/2c947138c345ae5700fc7ca4a2a6c341d078ea2e/data/html/options-panel.html) by 1

**Comment by alct** [comment]
Great :)

**Pull request closed without merging**
