### PR TITLE
HTML cleanup

### PR DESCRIPTION
**Pull request by alct**
### Fixed remaining whitespace/tab issues

Fixed few remaining tab/whitespace mixing issue following the merge.

### Reduced indentation level

No indentation for `body`'s direct children.

### CODE REVIEW

**Comment by dillbyrne** [comment]
:+1:

**Comment by alct** [comment]
Not related to this peculiar pull request but with HTML cleanup at large: are these lines still required?

- https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/html/options-panel.html#L44
- https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/html/options-panel.html#L67
- https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/html/options-panel.html#L155
- https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/html/options-panel.html#L342

**Comment by alct** [comment]
(updated lines number)

**Comment by dillbyrne** [comment]
@alct They are not needed anymore and can be removed

**Pull request merged**
