### PR TITLE
Improved "headers" tab

### PR DESCRIPTION
**Pull request by alct**
### Removed obsolete comment tags

Self-explanatory.

### Cleaned up "headers" tab markup

Used proper markup (`p` when needed, removed useless markup and `br`s). Instead of fixing the droplists on the right side, we include them right into the sentence.

*Note: we'll have to update locales, I've only updated the English ones (I can do it/get it done in `fr`, `de`, `it` and `nl`).*

`Referer` header will have the same behavior when more options are implemented (#110).

> [checkbox] Spoof Referer using [droplist: an empty value | a custom value]

### Improved "headers" tab layout

Increased vertical spacing among elements, improved "IP address" label and field position/size.

### Updated few strings related to "headers" tab

The changes made in the English locales (plus the updated markup and layout) are non-breaking. The other locales MUST not be updated, they SHOULD be. I suggest waiting for other updates before asking for translations.

###  Updated select elements style to better integrate them into the sentence

Self-explanatory.

### Alphabetically reordered options

Self-explanatory.

### Updated wording to reflect the other options'

Self-explanatory.

### Further improved select element style

Self-explanatory.

### Set the focus on the proper field when a custom option is chosen

Self-explanatory.

### Fixed alphabetical order

It fixes a previous copy/pasta error.

### Resized label and input field

Use all the available horizontal space (and make room for IPv6 addresses).

### Resized overall panel (rectangle rather than square)

Reduced width.

### CODE REVIEW

**Comment by alct** [comment]
noname

**Comment by dillbyrne** [comment]
Hey @alct Thanks for your work on this.  

Some points about this. The panel size needs to stay as it is otherwise certain options such as some android ones are wrapped is in the screenshot below. 
ras_preview7


Also I prefer to keep the UI consistent so having mixed dropdowns is not an option. I think we should pick one or the other. I like the look of the custom one you picked but I think it could do with being a bit darker for increased contrast.   

I think the proposed referer header option should be changed as we are not currently doing any spoofing so it makes no sense to say "spoof referer as" until the options exist.

The rest of the changes are fine.

I can merge your current changes and make the necessary adjustments or you can make the adjustments and then I can merge. Let me know and thanks again

**Comment by dillbyrne** [comment]
As for the locales . I wrote a quick and dirty python script which uses  https://github.com/terryyin/google-translate-python/blob/master/translate.py to bulk translate all the files from the en_US one. It is not perfect but it gets most of the heavy lifting out of the way. So once there are no more string changes to commit . I will do the translations and then add the updated files. They are translated using google translate so afterwards if you would like  you can have a look over them and see if there are any mistakes.

**Comment by alct** [comment]
Hold on :-) I'll comment/work on it tonight.

**Comment by dillbyrne** [comment]
@alct Sure no problem. There is no major rush  so if you can't do it tonight its fine, do it when you can.  I'm aiming for sometime next week to release 0.9.5.2 and the remaining issues in this milestone should not be too much trouble  so there is lots of time.

**Comment by alct** [comment]
> The panel size needs to stay at the size I had it at previously otherwise certain options such as some android ones are wrapped as in the screenshot below.

Crap. Let's get it wider and try to keep the rectangular shape. Using a square, we would be wasting a lot of horizontal space.

> Also I prefer to keep the UI consistent so having mixed dropdowns is not an option.

Agreed. I'm actually working tab after tab (started with Profile, now Headers, next will be Extras, etc.), having the same style for every `select` field is as simple as removing `#headers_tab_content` [here](https://github.com/alct/random-agent-spoofer/commit/bcf56ce90e90b11430c58360eb5c3c27a59e373b#diff-d27403c17a052ecc438390cd3c6731cfR188).

Will do.

> I think we should pick one or the other.

Agreed. I'd suggest to go for the custom one. Even though it is usually not recommend to [customize HTML forms](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/Styling_HTML_forms), given the fact that we have some control over the environment (browser) and given that our customization is quite "soft", it's a safe pick.

> On the other hand the default select will be that of the OS in use and users are already familiar with this so it may be best to keep the defaults in place.

The reason why we should go for the custom one is that the style of the `select` field isn't consistent among the various operating systems and it would be to much of burden to try and keep a consistent line-height between "regular" lines and lines containing such an element with a "default" (non-consistent) style.

> I like the look of the custom one you picked but I think it could do with being a bit darker for increased contrast.

Talking about consistency: the idea is to get completely rid of the current/old layout (`label` left aligned and `select` right aligned) and go for the new one - as seen in the screenshot - (`checkbox`, `label` and `select` in the same sentence).

For instance:

> [checkbox] Spoof Time Zone as [droplist: ...]
> [checkbox] Spoof Screen Size as [droplist: ...]

So, it is quite light on purpose so that it integrates better into the sentence and as a less important visual weight (the only element which stands out is the arrow which conveys a peculiar message: "there's a possible action here").

Here is an (extreme) example of a darker background to illustrate this point:

noname

> I think the proposed referer header option should be changed as we are not currently doing any spoofing so it makes no sense to say "spoof referer as" until the options exist.

Is it realistic to try to get it working for the next release? Its behavior would be quite simple:

> [checkbox] Spoof Referer using [droplist: empty value | custom value]

When the checkbox isn't check, no action is required by the addon. When it is checked, it defaults to simply stop passing the referer ("empty value"). When the "custom value" option is selected, it displays a new field (as for Via and X-Forwarded-For) and we use the value provided.

Later on, we could work on a third option, "dynamic value" (as discussed in #110) where, for instance, the referer would only be passed among the same domain.


P.S. what's your XMPP address? The one on your website, doesn't seem to work - I get a 404 server not found. If you don't want to to leave it here, drop me a line by e-mail (check my website).

**Comment by dillbyrne** [comment]
Hey @alct sorry about the delay in getting back to you.  my xmpp address and otr key fingerprint are both on https://dillbyrne.github.io/contact.html It should be working. Perhaps the server may have been down when you tried it. I was not online at the time but I generally am.  I'll email you too so you can contact me that way also.

The changes look really good. Nice job :+1: 

The `select` elements look good now that they are all consistent and the panel size accommodates all the profiles nicely.

>Is it realistic to try to get it working for the next release? Its behavior would be quite simple

I'm not yet sure how I'm going to go about implementing it. I could use a combination of firefox's built in options and map the combinations to specific selects or I could set the headers myself  and map them to selects.  I have not yet had a chance to look into it to compare both approaches. So I want to wait until I release 0.9.5.2 and do it in a future update.

I think for now having the label for the referer read "set referer as" would be better until  the header is actually being spoofed. 


Thanks again for your work on this .I really appreciate it

**Pull request merged**
